[package]
name = "provider_client"
version = "0.1.0"
authors = ["Jedrzej Stuczynski <jedrzej.stuczynski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"
tokio = { version = "0.2", features = ["full"] }

## internal
sfw-provider-requests = { path = "../../sfw-provider/sfw-provider-requests" }

## will be moved to proper dependencies once released
sphinx = { path = "../../../sphinx" }