language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
env:
  - RUST_TEST_THREADS=1
before_script:
  - rustup component add rustfmt
script:
  - cargo build
  - cargo test
  - cargo fmt -- --check