[package]
name = "nym-sfw-provider"
version = "0.1.0"
authors = ["Dave Hrycyszyn <futurechimp@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sphinx = { path = "../sphinx" }
tokio = { version = "0.2.4", features = ["full"] }
futures = "0.3.1"
curve25519-dalek = "1.2.3"
clap = "2.33.0"