[workspace]

members = [
    "clients/nym-client",
    "clients/directory-client",
    "clients/mix-client",
    "clients/provider-client",
    "clients/validator-client",
    "mixnode",
    "sfw-provider",
    "sfw-provider/sfw-provider-requests",
    "validator",
]
