[package]
build = "build.rs"
name = "nym-mixnode"
version = "0.1.0"
authors = ["Dave Hrycyszyn <futurechimp@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11.0"
clap = "2.33.0"
curve25519-dalek = "1.2.3"
futures = "0.3.1"
nym-client = { path = "../nym-client" }
sphinx = { path = "../sphinx" }
tokio = { version = "0.2", features = ["full"] }


[build-dependencies]
built = "0.3.2"