[workspace]

members = [
    "clients/nym-client",
    "clients/directory-client",
    "clients/mix-client",
    "clients/provider-client",
    "clients/validator-client",
    "common/addressing",
    "common/crypto",
    "common/topology",
    "mixnode",
    "sfw-provider",
    "sfw-provider/sfw-provider-requests",
]