[package]
name = "topology"
version = "0.1.0"
authors = ["Jedrzej Stuczynski <andrew@nymtech.net"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11.0"
curve25519-dalek = "1.2.3"
log = "0.4.8"
rand = "0.7.2"
serde = { version = "1.0.104", features = ["derive"] }

## internal
addressing = {path = "../addressing"}
directory_client = { path = "../../client/directory_client" }

## will be moved to proper dependencies once released
sphinx = { path = "../../../sphinx" }